// Generated by Selenium IDE

namespace WebTests.Bases;

public class TestBase
{
    public readonly ApplicationManager ApplicationManager;

    public TestBase(ApplicationManager manager)
    {
        ApplicationManager = manager;
    }
}